changelog:
  exclude:
    authors:
      - github-actions
      - renovate[bot]
      - dependabot[bot]

  categories:
    - title: 💥 Breaking Changes
      labels:
        - 'breaking'
      description: |
        Major updates or incompatible API changes. Please check your integration before upgrading.

    - title: ✨ New Features
      labels:
        - 'feat'

    - title: 🚀 Performance
      labels:
        - 'perf'

    - title: 🐛 Bug Fixes
      labels:
        - 'bug'

    - title: 📑 Documentation
      labels:
        - 'docs'
      description: |
        Updates to README, guides, or inline documentation.

    - title: 🧱 Refactors
      labels:
        - 'refactor'

    - title: 🧪 Tests
      labels:
        - 'test'

    - title: ⚠️ Deprecations
      labels:
        - 'deprecate'
      description: |
        APIs or features marked as deprecated, may be removed in future releases

    - title: ⚙️ Build & CI
      labels:
        - 'build'
        - 'ci'

    - title: 🧩 Other
      labels:
        - '*'
