name: 🐛 Bug 反馈
description: 报告一个 bug 来帮助我们改进项目
title: "[Bug]: xxx"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写这个 bug 报告！请尽可能详细地描述问题，这将帮助我们更快地定位和修复问题。

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug 描述
      description: 清楚简洁地描述这个 bug 是什么
      placeholder: 描述你遇到的问题...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 版本信息
      description: 你使用的是哪个版本？
      placeholder: 例如：v1.0.0
    validations:
      required: true

  - type: textarea
    id: others
    attributes:
      label: 📋 额外信息
      description: 添加任何其他有关问题的上下文信息
      placeholder: 环境信息、截图、错误日志、相关链接等...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ 确认
      description: 在提交之前，请确认以下内容
      options:
        - label: 我已经搜索了现有的 issues，确认这不是重复问题
          required: true
        - label: 我提供的信息是准确和完整的
          required: true
