name: PR Thanks

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read

jobs:
  comment:
    permissions:
      issues: write
      pull-requests: write
    if: github.event.pull_request.merged == true && github.repository == 'oljc/checkis'
    runs-on: ubuntu-latest
    steps:
      - name: Statistics
        id: statistics
        run: |
          PR_AUTHOR=$(echo "${{ github.event.pull_request.user.login }}")
          RESULT_DATA=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?author=${PR_AUTHOR}&per_page=5")
          DATA_LENGTH=$(echo $RESULT_DATA | jq 'if type == "array" then length else 0 end')
          echo "COUNT=$DATA_LENGTH" >> $GITHUB_OUTPUT
      - name: Comment
        if: steps.statistics.outputs.COUNT < 3
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ✨ Thank you for your contribution! PR has been successfully merged, we are glad to have you join us!

            ✨ 感谢您的贡献！PR 已顺利合并，我们很高兴有您的加入！

