name: Version

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          release-type: node
          config-file: .github/release-please-config.json
