name: Version

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Changelog
        uses: oljc/release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version-file: 'core/package.json'
          changelog-file: 'core/CHANGELOG.md'
          branch: 'main'
